from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: OurShop
    Generated by: Fabio Blanco (fablanco45@ucatolica.edu.co)
    Generated on 10/14/2021, 00:04:27
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="9YMUsLk66WOGc3Dz5dL5rH53KY99wF1zvatoBn7Lxzs",
                              project_name="My first Project",
                              job_name="OurShop")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8100/home"

    # 1. Click 'ION-MENU-BUTTON'
    ion_menu_button = driver.find_element(By.XPATH,
                                          "//ion-menu-button")
    ion_menu_button.click()

    # 2. Click 'My Account'
    my_account = driver.find_element(By.XPATH,
                                     "//ion-label[. = ' My Account']")
    my_account.click()

    # 3. Click 'ION-MENU'
    ion_menu = driver.find_element(By.XPATH,
                                   "//ion-menu")
    ion_menu.click()

    # 4. Click 'name'
    name = driver.find_element(By.XPATH,
                               "//input[@placeholder = 'Nombre']")
    name.click()

    # 5. Type 'Kevin editado' in 'name'
    name = driver.find_element(By.XPATH,
                               "//input[@placeholder = 'Nombre']")
    name.send_keys("Kevin editado")

    # 6. Click 'name1'
    name1 = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Apellido']")
    name1.click()

    # 7. Type 'Galindo Editado' in 'name1'
    name1 = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Apellido']")
    name1.send_keys("Galindo Editado")

    # 8. Click 'nickName'
    nickname = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Nombre de Usuario']")
    nickname.click()

    # 9. Type 'kevin1' in 'nickName'
    nickname = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Nombre de Usuario']")
    nickname.send_keys("kevin1")

    # 10. Click 'GUARDAR CAMBIOS'
    guardar_cambios = driver.find_element(By.XPATH,
                                          "//ion-button[. = 'Guardar Cambios']")
    guardar_cambios.click()
