from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Consultar Productos Login
    Generated by: JORGE ESTEBAN MUNOZ MAYA (jemunoz84@ucatolica.edu.co)
    Generated on 10/13/2021, 16:28:02
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="h_9TVkFfCi7Jv6icwuVAtuwE2SLnW8AiuNCKyFsMMoI",
                              project_name="My first Project",
                              job_name="Consultar Productos Login")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Consultar Productos Login."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8100/home"
    Email = "jemunoz84@ucatolica.edu.co"
    Password = "123456"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//ion-button[. = 'Login']")
    login.click()

    # 3. Click 'email'
    email = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Email']")
    email.click()

    # 4. Type '{Email}' in 'email'
    email = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Email']")
    email.send_keys(f'{Email}')

    # 5. Type '{Password}' in 'password'
    password = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Password']")
    password.send_keys(f'{Password}')

    # 6. Click 'Iniciar'
    iniciar = driver.find_element(By.XPATH,
                                  "//ion-button[. = 'Iniciar']")
    iniciar.click()

    # 7. Click 'SALIR'
    salir = driver.find_element(By.XPATH,
                                "//ion-button[. = 'Salir']")
    salir.click()
