from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Cristian Yesid Padilla Perea's first project
    Package: TestProject.Generated.Tests.CristianYesidPadillaPereasFirstProject
    Test: Registro fallido
    Generated by: Diego Alejandro Correa Diaz (dacorread05@gmail.com)
    Generated on 10/13/2021, 15:49:47
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="o8v_X93IdHO0IUPn0YdA3-MefybVO_j1d-rJd7FumiQ",
                              project_name="Cristian Yesid Padilla Perea's first project",
                              job_name="Registro fallido")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8100/home"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Sign Up'
    sign_up = driver.find_element(By.XPATH,
                                  "//ion-button[. = 'Sign Up']")
    sign_up.click()

    # 3. Click 'name'
    name = driver.find_element(By.XPATH,
                               "//input[@placeholder = 'Nombre']")
    name.click()

    # 4. Type '123Esteban' in 'name'
    name = driver.find_element(By.XPATH,
                               "//input[@placeholder = 'Nombre']")
    name.send_keys("123Esteban")

    # 5. Type '123Munoz' in 'lastName'
    lastname = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Apellido']")
    lastname.send_keys("123Munoz")

    # 6. Type 'jemunoz84' in 'nickName'
    nickname = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Nombre de Usuario']")
    nickname.send_keys("jemunoz84")

    # 7. Type 'cl 137b #13-80' in 'address'
    address = driver.find_element(By.XPATH,
                                  "//input[@placeholder = 'Dirección']")
    address.send_keys("cl 137b #13-80")

    # 8. Type 'jemunoz84@o' in 'email'
    email = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Email']")
    email.send_keys("jemunoz84@o")

    # 9. Click 'email'
    email = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Email']")
    email.click()

    # 10. Type 'jemunoz84@' in 'email'
    email = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Email']")
    email.send_keys("jemunoz84@")

    # 11. Click 'password'
    password = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Contraseña']")
    password.click()

    # 12. Type 'jemunoz84' in 'password'
    password = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Contraseña']")
    password.send_keys("jemunoz84")

    # 13. Type 'jemunos' in 'ion-input-6'
    ion_input_6 = driver.find_element(By.CSS_SELECTOR,
                                      "[name='ion-input-6']")
    ion_input_6.send_keys("jemunos")

    # 14. Click 'role'
    role = driver.find_element(By.XPATH,
                               "//ion-select[@placeholder = 'Seleccione su tipo de usuario']")
    role.click()

    # 15. Click 'ION-RADIO1'
    ion_radio1 = driver.find_element(By.XPATH,
                                     "//ion-item[2]/ion-radio")
    ion_radio1.click()

    # 16. Click 'Registrarme'
    registrarme = driver.find_element(By.XPATH,
                                      "//ion-button[. = 'Registrarme']")
    registrarme.click()

    # 17. Click 'Registrarme'
    registrarme = driver.find_element(By.XPATH,
                                      "//ion-button[. = 'Registrarme']")
    registrarme.click()
