from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Modificar Usuario
    Generated by: JORGE ESTEBAN MUNOZ MAYA (jemunoz84@ucatolica.edu.co)
    Generated on 10/13/2021, 16:29:37
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="h_9TVkFfCi7Jv6icwuVAtuwE2SLnW8AiuNCKyFsMMoI",
                              project_name="My first Project",
                              job_name="Modificar Usuario")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Modificar Usuario."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8100/home"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//ion-button[. = 'Login']")
    login.click()

    # 3. Click 'email'
    email = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Email']")
    email.click()

    # 4. Type 'jemunoz84@ucatolica.edu.co' in 'email'
    email = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Email']")
    email.send_keys("jemunoz84@ucatolica.edu.co")

    # 5. Type '123456' in 'password'
    password = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Password']")
    password.send_keys("123456")

    # 6. Click 'Iniciar'
    iniciar = driver.find_element(By.XPATH,
                                  "//ion-button[. = 'Iniciar']")
    iniciar.click()

    # 7. Click 'ION-MENU-BUTTON'
    ion_menu_button = driver.find_element(By.XPATH,
                                          "//ion-menu-button")
    ion_menu_button.click()

    # 8. Click 'My Account'
    my_account = driver.find_element(By.XPATH,
                                     "//ion-label[. = ' My Account']")
    my_account.click()

    # 9. Click 'ION-MENU'
    ion_menu = driver.find_element(By.XPATH,
                                   "//ion-menu")
    ion_menu.click()

    # 10. Click 'address'
    address = driver.find_element(By.XPATH,
                                  "//input[@placeholder = 'Dirección']")
    address.click()

    # 11. Type 'usme :D' in 'address'
    address = driver.find_element(By.XPATH,
                                  "//input[@placeholder = 'Dirección']")
    address.send_keys("usme :D")

    # 12. Click 'Guardar Cambios'
    guardar_cambios = driver.find_element(By.XPATH,
                                          "//ion-button[. = 'Guardar Cambios']")
    guardar_cambios.click()
