from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Consultar productos
    Generated by: JORGE ESTEBAN MUNOZ MAYA (jemunoz84@ucatolica.edu.co)
    Generated on 10/13/2021, 16:30:13
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="h_9TVkFfCi7Jv6icwuVAtuwE2SLnW8AiuNCKyFsMMoI",
                              project_name="My first Project",
                              job_name="Consultar productos")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Consultar productos."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8100/home"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')
