from addons.string_utils import StringUtils
from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Cristian Yesid Padilla Perea's first project
    Package: TestProject.Generated.Tests.CristianYesidPadillaPereasFirstProject
    Test: Consultar Usuario Fallido
    Generated by: Diego Alejandro Correa Diaz (dacorread05@gmail.com)
    Generated on 10/13/2021, 15:45:49
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="o8v_X93IdHO0IUPn0YdA3-MefybVO_j1d-rJd7FumiQ",
                              project_name="Cristian Yesid Padilla Perea's first project",
                              job_name="Consultar Usuario Fallido")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8100/home"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Sign Up'
    sign_up = driver.find_element(By.XPATH,
                                  "//ion-button[. = 'Sign Up']")
    sign_up.click()

    # 3. Click 'name'
    name = driver.find_element(By.XPATH,
                               "//input[@placeholder = 'Nombre']")
    name.click()

    # 4. Type 'cristian ' in 'name'
    name = driver.find_element(By.XPATH,
                               "//input[@placeholder = 'Nombre']")
    name.send_keys("cristian ")

    # 5. Type 'padilla' in 'lastName'
    lastname = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Apellido']")
    lastname.send_keys("padilla")

    # 6. Type 'cristacho' in 'nickName'
    nickname = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Nombre de Usuario']")
    nickname.send_keys("cristacho")

    # 7. Type 'kr79f#45-56' in 'address'
    address = driver.find_element(By.XPATH,
                                  "//input[@placeholder = 'Dirección']")
    address.send_keys("kr79f#45-56")

    # 8. Type 'pruebacristancho@gmail.com' in 'email'
    email = driver.find_element(By.XPATH,
                                "//input[@placeholder = 'Email']")
    email.send_keys("pruebacristancho@gmail.com")

    # 9. Type '123456' in 'password'
    password = driver.find_element(By.XPATH,
                                   "//input[@placeholder = 'Contraseña']")
    password.send_keys("123456")

    # 10. Type '123456' in 'ion-input-6'
    ion_input_6 = driver.find_element(By.CSS_SELECTOR,
                                      "[name='ion-input-6']")
    ion_input_6.send_keys("123456")

    # 11. Click 'role'
    role = driver.find_element(By.XPATH,
                               "//ion-select[@placeholder = 'Seleccione su tipo de usuario']")
    role.click()

    # 12. Click 'ION-RADIO1'
    ion_radio1 = driver.find_element(By.XPATH,
                                     "//ion-item[2]/ion-radio")
    ion_radio1.click()

    # 13. Click 'Registrarme'
    registrarme = driver.find_element(By.XPATH,
                                      "//ion-button[. = 'Registrarme']")
    registrarme.click()

    # 14. Click 'ION-MENU-BUTTON'
    ion_menu_button = driver.find_element(By.XPATH,
                                          "//ion-menu-button")
    ion_menu_button.click()

    # 15. Click 'My Account'
    my_account = driver.find_element(By.XPATH,
                                     "//ion-label[. = ' My Account']")
    my_account.click()

    # 16. Click 'ION-MENU'
    ion_menu = driver.find_element(By.XPATH,
                                   "//ion-menu")
    ion_menu.click()

    # 17. Is 'name' not present or invisible?
    name = driver.find_element(By.XPATH,
                               "//input[@placeholder = 'Nombre']")
    assert not name.is_displayed()

    # 18. Click 'name'
    name = driver.find_element(By.XPATH,
                               "//input[@placeholder = 'Nombre']")
    name.click()

    # 19. Count how many strings are present in ''[name]'' with a given delimiter ''[NONE]''
    step_output = driver.addons().execute(
        StringUtils.countstrings(
            inputString="[name]",
            delimiter=""))
