from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import project_parameters
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Cristian Yesid Padilla Perea's first project
    Package: TestProject.Generated.Tests.CristianYesidPadillaPereasFirstProject
    Test: Registrar Producto fallido
    Generated by: Diego Alejandro Correa Diaz (dacorread05@gmail.com)
    Generated on 10/13/2021, 15:57:18
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="o8v_X93IdHO0IUPn0YdA3-MefybVO_j1d-rJd7FumiQ",
                              project_name="Cristian Yesid Padilla Perea's first project",
                              job_name="Registrar Producto fallido")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8100/home"
    email = "jemunoz@ucatolica.edu.co"
    password = "123456"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//ion-button[. = 'Login']")
    login.click()

    # 3. Click 'email1'
    email1 = driver.find_element(By.XPATH,
                                 "//input[@placeholder = 'Email']")
    email1.click()

    # 4. Type '{project_parameters.email}' in 'email1'
    email1 = driver.find_element(By.XPATH,
                                 "//input[@placeholder = 'Email']")
    email1.send_keys(f'{project_parameters.email}')

    # 5. Click 'password1'
    password1 = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Password']")
    password1.click()

    # 6. Type '{project_parameters.password}' in 'password1'
    password1 = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Password']")
    password1.send_keys(f'{project_parameters.password}')

    # 7. Click 'Iniciar'
    iniciar = driver.find_element(By.XPATH,
                                  "//ion-button[. = 'Iniciar']")
    iniciar.click()
