from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Cristian Yesid Padilla Perea's first project
    Package: TestProject.Generated.Tests.CristianYesidPadillaPereasFirstProject
    Test: Registro producto
    Generated by: Diego Alejandro Correa Diaz (dacorread05@gmail.com)
    Generated on 10/13/2021, 15:47:03
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="o8v_X93IdHO0IUPn0YdA3-MefybVO_j1d-rJd7FumiQ",
                              project_name="Cristian Yesid Padilla Perea's first project",
                              job_name="Registro producto")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8100/home"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//ion-button[. = 'Login']")
    login.click()

    # 3. Click 'email1'
    email1 = driver.find_element(By.XPATH,
                                 "//input[@placeholder = 'Email']")
    email1.click()

    # 4. Type 'jemunoz84@ucatolica.edu.co' in 'email1'
    email1 = driver.find_element(By.XPATH,
                                 "//input[@placeholder = 'Email']")
    email1.send_keys("jemunoz84@ucatolica.edu.co")

    # 5. Click 'password1'
    password1 = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Password']")
    password1.click()

    # 6. Type '123456' in 'password1'
    password1 = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Password']")
    password1.send_keys("123456")

    # 7. Click 'Iniciar'
    iniciar = driver.find_element(By.XPATH,
                                  "//ion-button[. = 'Iniciar']")
    iniciar.click()

    # 8. Click 'ION-FAB-BUTTON'
    ion_fab_button = driver.find_element(By.XPATH,
                                         "//ion-fab/ion-fab-button")
    ion_fab_button.click()

    # 9. Click 'add'
    add = driver.find_element(By.CSS_SELECTOR,
                              "[name='add']")
    add.click()

    # 10. Click 'ion-input-2'
    ion_input_2 = driver.find_element(By.CSS_SELECTOR,
                                      "[name='ion-input-2']")
    ion_input_2.click()

    # 11. Type 'Telefono' in 'ion-input-2'
    ion_input_2 = driver.find_element(By.CSS_SELECTOR,
                                      "[name='ion-input-2']")
    ion_input_2.send_keys("Telefono")

    # 12. Click 'ion-input-3'
    ion_input_3 = driver.find_element(By.CSS_SELECTOR,
                                      "[name='ion-input-3']")
    ion_input_3.click()

    # 13. Type '100000' in 'ion-input-3'
    ion_input_3 = driver.find_element(By.CSS_SELECTOR,
                                      "[name='ion-input-3']")
    ion_input_3.send_keys("100000")

    # 14. Click 'ion-textarea-0'
    ion_textarea_0 = driver.find_element(By.CSS_SELECTOR,
                                         "[name='ion-textarea-0']")
    ion_textarea_0.click()

    # 15. Type 'Este es un telefono' in 'ion-textarea-0'
    ion_textarea_0 = driver.find_element(By.CSS_SELECTOR,
                                         "[name='ion-textarea-0']")
    ion_textarea_0.send_keys("Este es un telefono")

    # 16. Click 'ion-input-61'
    ion_input_61 = driver.find_element(By.CSS_SELECTOR,
                                       "[name='ion-input-6']")
    ion_input_61.click()

    # 17. Type '10' in 'ion-input-61'
    ion_input_61 = driver.find_element(By.CSS_SELECTOR,
                                       "[name='ion-input-6']")
    ion_input_61.send_keys("10")

    # 18. Click 'Publicar'
    publicar = driver.find_element(By.XPATH,
                                   "//ion-button[. = 'Publicar']")
    publicar.click()
