from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Cristian Yesid Padilla Perea's first project
    Package: TestProject.Generated.Tests.CristianYesidPadillaPereasFirstProject
    Test: Eliminar producto
    Generated by: Diego Alejandro Correa Diaz (dacorread05@gmail.com)
    Generated on 10/13/2021, 15:49:57
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="o8v_X93IdHO0IUPn0YdA3-MefybVO_j1d-rJd7FumiQ",
                              project_name="Cristian Yesid Padilla Perea's first project",
                              job_name="Eliminar producto")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8100/home"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Login'
    login = driver.find_element(By.XPATH,
                                "//ion-button[. = 'Login']")
    login.click()

    # 3. Click 'email1'
    email1 = driver.find_element(By.XPATH,
                                 "//input[@placeholder = 'Email']")
    email1.click()

    # 4. Type 'sebas@gmail.com' in 'email1'
    email1 = driver.find_element(By.XPATH,
                                 "//input[@placeholder = 'Email']")
    email1.send_keys("sebas@gmail.com")

    # 5. Click 'password1'
    password1 = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Password']")
    password1.click()

    # 6. Click 'password1'
    password1 = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Password']")
    password1.click()

    # 7. Type '123456' in 'password1'
    password1 = driver.find_element(By.XPATH,
                                    "//input[@placeholder = 'Password']")
    password1.send_keys("123456")

    # 8. Click 'Iniciar'
    iniciar = driver.find_element(By.XPATH,
                                  "//ion-button[. = 'Iniciar']")
    iniciar.click()

    # 9. Click 'Silla de escritorio'
    silla_de_escritorio = driver.find_element(By.XPATH,
                                              "//ion-card-title[. = 'Silla de escritorio']")
    silla_de_escritorio.click()

    # 10. Click 'Eliminar'
    eliminar = driver.find_element(By.XPATH,
                                   "//ion-button[. = 'Eliminar']")
    eliminar.click()
